version: '3.5'
services:
  ui:
    container_name: jobba-ui
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    networks:
      - nodeapp-network
    depends_on: 
      - api
    environment:
      - HOST=0.0.0.0
      - VIRTUAL_HOST=vue-node-starter.localhost
    volumes:
      - ./frontend:/usr/src/app
  api:
    container_name: jobba-api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOSTNAME : database
    ports:
      - '5001:5001'
    networks:
      - nodeapp-network
    depends_on: 
      - database
  database:
    container_name: jobba-mongo
    image: mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017:27017'
    networks:
      - nodeapp-network
  
networks:
  nodeapp-network:
    driver: bridge